apiVersion: v1
kind: Service
metadata:
    name: "myakscluster-29e4"
    labels:
        app: "myakscluster-29e4"
spec:
    type: LoadBalancer
    ports:
    - port: 8088
      targetPort: 8088
      protocol: TCP
      name: http
    selector:
        app: "myakscluster-29e4"